apiVersion: v2
name: elevatedpos
description: ElevatedPOS Unified Commerce Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - pos
  - commerce
  - retail
maintainers:
  - name: ElevatedPOS Team
