apiVersion: v1
kind: ServiceAccount
metadata:
  name: elevatedpos-app
  namespace: elevatedpos
  labels:
    app.kubernetes.io/name: elevatedpos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elevatedpos-role
  namespace: elevatedpos
  labels:
    app.kubernetes.io/name: elevatedpos
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elevatedpos-rolebinding
  namespace: elevatedpos
  labels:
    app.kubernetes.io/name: elevatedpos
subjects:
  - kind: ServiceAccount
    name: elevatedpos-app
    namespace: elevatedpos
roleRef:
  kind: Role
  name: elevatedpos-role
  apiGroup: rbac.authorization.k8s.io
