import { pgTable, uuid, varchar, boolean, timestamp, jsonb, decimal, integer, text, date } from 'drizzle-orm/pg-core';

export const customers = pgTable('customers', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  dob: date('dob'),
  gender: varchar('gender', { length: 20 }),
  addressLine1: varchar('address_line1', { length: 255 }),
  suburb: varchar('suburb', { length: 100 }),
  state: varchar('state', { length: 50 }),
  postcode: varchar('postcode', { length: 20 }),
  country: varchar('country', { length: 2 }).default('AU'),
  company: varchar('company', { length: 255 }),
  abn: varchar('abn', { length: 20 }),
  tags: jsonb('tags').notNull().default([]),
  marketingOptIn: boolean('marketing_opt_in').notNull().default(false),
  marketingOptInAt: timestamp('marketing_opt_in_at', { withTimezone: true }),
  householdId: uuid('household_id'),
  rfmScore: varchar('rfm_score', { length: 10 }),
  lifetimeValue: decimal('lifetime_value', { precision: 12, scale: 4 }).notNull().default('0'),
  visitCount: integer('visit_count').notNull().default(0),
  lastPurchaseAt: timestamp('last_purchase_at', { withTimezone: true }),
  churnRiskScore: decimal('churn_risk_score', { precision: 5, scale: 4 }),
  preferredLanguage: varchar('preferred_language', { length: 10 }).default('en'),
  dietaryPreferences: jsonb('dietary_preferences').notNull().default([]),
  allergenAlerts: jsonb('allergen_alerts').notNull().default([]),
  notes: text('notes'),
  source: varchar('source', { length: 50 }).default('pos'),
  gdprDeleted: boolean('gdpr_deleted').notNull().default(false),
  gdprDeletedAt: timestamp('gdpr_deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const storeCreditAccounts = pgTable('store_credit_accounts', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  balance: decimal('balance', { precision: 12, scale: 4 }).notNull().default('0'),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const storeCreditTransactions = pgTable('store_credit_transactions', {
  id: uuid('id').primaryKey().defaultRandom(),
  accountId: uuid('account_id').notNull().references(() => storeCreditAccounts.id),
  orgId: uuid('org_id').notNull(),
  type: varchar('type', { length: 50 }).notNull(),
  amount: decimal('amount', { precision: 12, scale: 4 }).notNull(),
  orderId: uuid('order_id'),
  notes: text('notes'),
  employeeId: uuid('employee_id').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
